### ISSUE TITLE
Replicate conan hoot install

### ISSUE THREAD

**Issue by jasonsurratt** [epochgeo/pyhoot#1] opened 2022-02-09 17:09 UTC
Please install cenos7 vm & verify the conan/hoot install:

* Install Conan following the instructions for hoot/conan prerequisites here: https://github.com/epochgeo/hootenanny-conan
* Install libphonenumber with `make`: https://github.com/epochgeo/conan-libphonenumber
* Install liboauthcpp-conan: https://github.com/epochgeo/liboauthcpp-conan
* Install conan-libnode: https://github.com/epochgeo/conan-libnode

There are guaranteed to be errors of omission, please reach out when you hit them.

**Comment by bwitham** [comment] 2022-09-22 21:01
dupe of issue in hootenanny-conan

**Closed by bwitham** 2022-09-22 21:01 UTC
